version: '3'

services:
  redis:
    image: redis:6.0
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  mysql:
    image: mysql:5.7.36
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234qWer
    volumes:
      - /d/data/mysql:/var/lib/mysql
  zookeeper:
    image: zookeeper:3.6
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
#  admin:
#    image: apache/dubbo-admin
#    container_name: dubbo-admin
#    restart: always
#    depends_on:
#      - zookeeper
#    ports:
#      - 8081:8080
#    environment:
#      - admin.registry.address=zookeeper://zookeeper:2181
#      - admin.config-center=zookeeper://zookeeper:2181
#      - admin.metadata-report.address=zookeeper://zookeeper:2181